version: '3'

services:
  db:     
      image: mysql:5.7       
      command: --default-authentication-plugin=mysql_native_password          
      environment:            
          MYSQL_ROOT_PASSWORD: supersecret         
          MYSQL_DATABASE: testapp           
          MYSQL_USER: root           
          MYSQL_PASSWORD: supersecret      
      ports:            
          - 3306:3306
  
  springboot:
    depends_on:
      - db
    build:
      context: Springboot # Use an image built from the specified dockerfile in the `` directory.
      dockerfile: Dockerfile
    ports:
        - 8081:8081            #$SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    #environment:
      #SPRING_APPLICATION_JSON: '{
        #"spring.datasource.url"  : "jdbc:mysql://db:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?useSSL=false",
        #"spring.datasource.username" : "$MYSQLDB_USER",
        #"spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
        #"spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        #"spring.jpa.hibernate.ddl-auto" : "update"
      #}'
    #volumes:
      #- .m2:/root/.m2
    #stdin_open: true
    #tty: true

  #angular:
   #restart: always
    #depends_on:
      #- springboot



volumes:
  mysql-data:
