version: '3'

services:
 teachteam-mysql-db:
        image: mysql:8.0
        container_name: teachteam-mysql-db
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: 123456
            MYSQL_USER: techteam
            MYSQL_PASSWORD: 123456Aa@
            MYSQL_ROOT_HOST: '%'
  
  springboot:
    depends_on:
      - teachteam-mysql-db
    build:
      context: Springboot # Use an image built from the specified dockerfile in the `` directory.
      dockerfile: Dockerfile
    ports:
        - 8081:8081            #$SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    #environment:
      #SPRING_APPLICATION_JSON: '{
        #"spring.datasource.url"  : "jdbc:mysql://db:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?useSSL=false",
        #"spring.datasource.username" : "$MYSQLDB_USER",
        #"spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
        #"spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        #"spring.jpa.hibernate.ddl-auto" : "update"
      #}'
    #volumes:
      #- .m2:/root/.m2
    #stdin_open: true
    #tty: true

  #angular:
   #restart: always
    #depends_on:
      #- springboot



#volumes:
  #mysql-data:
